apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: techdoc-test-1-sept18 
  janus-idp.io/tekton: techdoc-test-1-sept18
  backstage.io/kubernetes-id: techdoc-test-1-sept18
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: techdoc-test-1-sept18
resources: 
- application-dev.yaml