apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: techdoc-test-1-sept18
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: techdoc-test-1-sept18 
  name: techdoc-test-1-sept18
spec:
  ports:
  - port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app.kubernetes.io/instance: techdoc-test-1-sept18 
