apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: techdoc-test-1-sept18
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/techdoc-test-1-sept18:af0088c28abfa21db98c9206cb522fd2eee570c2@sha256:cfff544fa1cb449a2c65b55d0b3aafb9c64a1c66410d1d7cfb7767c8f956affd # use pre-built to bootstrap 
          name: app-inference
